language: haxe

haxe:
  - "3.2.0"
  - development

env:
  - TARGET=flash
  - TARGET=neko
  - TARGET=cpp
  - TARGET=html5

install:
  - haxelib install hxcpp > /dev/null
  - haxelib install flixel > /dev/null
  - haxelib install flixel-addons > /dev/null
  - haxelib list

script:
  - haxelib run lime build $TARGET
